### ISSUE TITLE
[온보딩] UI 구현

### ISSUE THREAD

**Issue by prestonk162** [boostcampwm-2022/iOS06-NearTalk#10]
# Task

- [x]  로고
- [x]  프로필 사진 클릭시 PHPickerViewController
- [x]  닉네임 TextField
    - [x]  유효성 검사
        - [x]  길이: 최소5 최대 20자
        - [x]  영 소문자, 숫자, 특수기호(_-)만 사용 가능하게 한다.
- [x]  상태메세지 TextField
    - [x]  유효성 검사
        - [x]  길이: 최대 50자
- [x]  완료 버튼
    - [ ]  메인화면 이동
